Save dataset id to state
iossifovlab/gpfjs pull request #1078
Opened 2024-07-05 13:03 UTC by IlinaGergova

## Background

Saving Dataset object in state causes bugs.

## Aim

To save dataset id only in state.

## Implementation

Save dataset id in state and if the component need the dataset it makes request using datasetsService method getDataset(datasetId: string) when it loads the id from state. This led to issues when validating regions filter after loading a query (share/save query) - genome wasn't passed on time. So the way of passing the genome is changed.

2024-07-08 09:03 UTC, IvoStefanov requested changes

2024-07-10 10:47 UTC, iordanivanov approved these changes

2024-07-10 10:47 UTC, iordanivanov commented on src/app/regions-filter/regions-filter.component.ts
> +  public constructor(protected store: Store, private datsetsService: DatasetsService) {
typo: `datsetsService`
also, why is the datasets service injected here? I don't see it being used

2024-07-10 10:49 UTC, iordanivanov commented
I also noticed a 404 error on your branch where the app was making requests to `datasets/details`, but this might not be from your changes

2024-07-12 09:26 UTC, IvoStefanov approved these changes

2024-07-12 09:26 UTC, merged