Agp category filtering
iossifovlab/gpfjs pull request #532
Opened 2021-06-03 07:16 UTC by joankosev

2021-06-04 08:14 UTC, iordanivanov requested changes

2021-06-04 08:14 UTC, iordanivanov commented on src/app/autism-gene-profiles-block/autism-gene-profiles-block.component.ts
> +    this.tableConfig = cloneDeep(this.tableConfig);
please make a ticket for this

2021-06-04 08:14 UTC, iordanivanov commented on src/app/autism-gene-profiles-table/autism-gene-profiles-table.component.ts
> +    this.shownGenomicScoresCategories = cloneDeep(this.config.genomicScores);
this pair of cloneDeep calls seem unnecessary

2021-06-08 06:47 UTC, IvoTod approved these changes

2021-06-09 13:19 UTC, merged