Dataset statistics pedigree update
iossifovlab/gpfjs pull request #621
Opened 2022-10-27 12:45 UTC by joankosev

Update dataset statistics "families by pedigree" table
- make pedigrees clickboxes bigger
- add the family count to the modal as well
- change mouseover highlight from tr to td

2022-10-31 08:19 UTC, IvoStefanov requested changes
Write unit tests

2022-10-31 08:19 UTC, IvoStefanov commented on src/app/variant-reports/common-reports-pedigree-cell/common-reports-pedigree-cell.component.ts
> +
Write test for openModal

2022-10-31 08:19 UTC, IvoStefanov commented on src/app/pedigree/pedigree.component.ts
Write test for openModal

2022-10-31 08:21 UTC, IvoStefanov requested changes
Write unit tests

2022-10-31 08:21 UTC, IvoStefanov commented on src/app/variant-reports/common-reports-pedigree-cell/common-reports-pedigree-cell.component.ts
> +  public openModal(): void {
Write test for openModal

2022-10-31 08:21 UTC, IvoStefanov commented on src/app/pedigree/pedigree.component.ts
> +  public openModal(): void {
Write test for openModal

2022-11-02 14:42 UTC, livovachkov approved these changes

2022-11-07 10:07 UTC, merged