Function template optimization
iossifovlab/gpfjs pull request #631
Opened 2022-11-16 13:46 UTC by livovachkov

## Background

Functions in templates are pretty much almost always a bad idea because they are called on the change detection cycle. This usually affects the performance because if some demanding function is called many times it slows down the workflow.

## Aim

The aim is to remove as many template calls that are called often. This will impact positively the performance and will make the workflow much easier. 

## Implementation

The implementation consists of using the change detection cycle the right way and as a tool and adding pipes that are not as expensive and demanding as function calls. Unit tests for them are also added.

2022-11-22 11:55 UTC, joankosev commented
New bug introduced in the phenotype browser - swapping from one tool to phenotype browser renders random amount of rows in the phenotype browser table. The user needs to trigger change detection in order for the rest to load. Same bug exists when swapping measures.

to reproduce:
SFARI_SPARK_WES_1_CONSORTIUM, data-hg38-production
https://user-images.githubusercontent.com/50270882/203307746-6bf7af88-c882-4db2-88ff-fdc9d778d23b.mp4


This bug doesn't seem to exist on master branch

2022-11-22 14:20 UTC, joankosev commented
New bug introduced with table header resizing... The behaviour in master branch is also not ideal, so will make a new issue about it

2022-11-22 14:26 UTC, joankosev commented
See if you can remove getBackgroundColor() in enrichment-table-row component

2022-12-08 14:10 UTC, livovachkov commented
> New bug introduced in the phenotype browser - swapping from one tool to phenotype browser renders random amount of rows in the phenotype browser table. The user needs to trigger change detection in order for the rest to load. Same bug exists when swapping measures.
> 
> to reproduce: SFARI_SPARK_WES_1_CONSORTIUM, data-hg38-production https://user-images.githubusercontent.com/50270882/203307746-6bf7af88-c882-4db2-88ff-fdc9d778d23b.mp4
> 
> This bug doesn't seem to exist on master branch

Can't reproduce this bug

2022-12-08 14:41 UTC, livovachkov commented
> See if you can remove getBackgroundColor() in enrichment-table-row component

Added pipe for enrichment table row. The branch is ready for re-review.

2022-12-13 10:20 UTC, joankosev requested changes

2022-12-13 14:18 UTC, joankosev commented
See
contrastAdjust() - src/app/enrichment-table/enrichment-table-row.component.ts
getVariantsCount() - src/app/genotype-preview-model/genotype-preview.ts

2022-12-16 12:27 UTC, joankosev commented
made a new issue for getVariantsCount() - #681

2022-12-16 12:28 UTC, joankosev approved these changes

2022-12-16 12:29 UTC, merged