Backwards functionality fix #662
iossifovlab/gpfjs pull request #669
Opened 2022-12-12 14:06 UTC by livovachkov

Backward functionality doesn't work on Firefox but works on Chrome. This bug is due to routing issues and improper handling of redirects(as there is a redirect loop that is happening in the datasets component).
The fix is temporary due to potentially forthcoming dataset component rework.

2022-12-13 10:08 UTC, joankosev requested changes

2022-12-13 10:08 UTC, joankosev commented
This introduces a bug with navigating backwards with mixed url from side-nav and dataset tools

2022-12-13 10:43 UTC, livovachkov commented on src/app/datasets/datasets.component.ts
> +import { ActivatedRoute, NavigationEnd, NavigationStart, Params, Router } from '@angular/router';
Outdated

2022-12-14 13:54 UTC, joankosev approved these changes

2022-12-14 13:56 UTC, merged