Gene plot unit tests
iossifovlab/gpfjs pull request #693
Opened 2023-01-18 09:10 UTC by livovachkov

## Background

There are not enough unit tests in the gene plot. This creates issues that are undetected.

## Aim

Write unit tests for the gene plot. This can help to find undetected issues and issues that are changed.

## Implementation

Write unit tests.

2023-01-25 11:34 UTC, iordanivanov requested changes

2023-01-25 11:34 UTC, iordanivanov commented on src/app/gene-plot/gene-plot.component.spec.ts
> +    ])].forEach((trans, i) => {
Why do we need an array with a forEach in this unit test, considering the array has just one element?

2023-01-25 11:34 UTC, iordanivanov commented on src/app/gene-plot/gene-plot.component.ts
> +  public drawTranscript(
Change back to private

2023-01-27 15:23 UTC, joankosev approved these changes

2023-01-27 15:26 UTC, iordanivanov approved these changes

2023-01-27 15:26 UTC, merged