Gene browser, pheno browser and autism gene profiles now support esca…
iossifovlab/gpfjs pull request #762
Opened 2023-02-23 12:57 UTC by livovachkov

## Background

Currently, some components support an escape key in order to cancel inputs. This is quite inconsistent as others do not have such support.

## Aim

Provide more consistent handling of escape and other keybindings.

## Implementation

Closes #760.

2023-02-24 09:36 UTC, joankosev requested changes
after pressing escape in gene browser, the input loses focus

2023-02-24 10:03 UTC, joankosev commented
remove AGP clear rows keybind escape; remove it from the keybinds list as well

2023-02-24 10:04 UTC, joankosev commented on src/app/autism-gene-profiles-table/autism-gene-profiles-table.component.ts
> +  @HostListener('document:keydown.esc')
replace hostlistener with (keydown.escape)="..."

2023-02-24 13:39 UTC, joankosev requested changes
also update keybind tooltip
![image](https://user-images.githubusercontent.com/50270882/221192672-18fba872-882a-45af-8e7e-a79258446de3.png)

2023-02-24 13:39 UTC, joankosev commented on src/app/autism-gene-profiles-table/autism-gene-profiles-table.component.ts
> +    if (document.activeElement === searchBox && this.searchBox.nativeElement.value !== '') {
useless if, (keydown.escape) already ensures the focused element is the input

2023-02-24 13:41 UTC, joankosev commented
spamming escape button on gene browser search unfocuses the input

2023-02-24 13:43 UTC, joankosev commented
why clear gene browser search on mouse click?

2023-02-27 08:48 UTC, joankosev commented
> also update keybind tooltip ![image](https://user-images.githubusercontent.com/50270882/221192672-18fba872-882a-45af-8e7e-a79258446de3.png)

^

2023-02-27 08:48 UTC, joankosev requested changes
-

2023-02-27 10:08 UTC, livovachkov commented
> spamming escape button on gene browser search unfocuses the input

This has been done intentionally.

2023-02-27 11:55 UTC, joankosev commented
1) when navigating to the tool, the search input should be focused;
2) when clicking on the input field, don't clear it - clear only after a gene has been selected;
3) after typing a valid gene (without clicking on the dropdown menu) and pressing enter, the dropdown should hide and the input should unfocus - equal behaviour as if dropdown was clicked
4) bug - when navigating to the gene browser and typing a gene, sometimes the dropdown won't show (works with ctrl+c/v). When the dropdown is hidden, you can make it appear after pressing any key on the keyboard (change detection?)
5) dropdown flickers when pressing escape once
6) pressing escape shouldn't unfocus the input

2023-03-14 13:05 UTC, joankosev commented
> 1. when navigating to the tool, the search input should be focused;
> 2. when clicking on the input field, don't clear it - clear only after a gene has been selected;
> 3. after typing a valid gene (without clicking on the dropdown menu) and pressing enter, the dropdown should hide and the input should unfocus - equal behaviour as if dropdown was clicked
> 4. bug - when navigating to the gene browser and typing a gene, sometimes the dropdown won't show (works with ctrl+c/v). When the dropdown is hidden, you can make it appear after pressing any key on the keyboard (change detection?)
> 5. dropdown flickers when pressing escape once
> 6. pressing escape shouldn't unfocus the input

7. bug in gene browser - typing a gene and then pressing go would clear the input and freeze the request

2023-03-30 11:35 UTC, joankosev commented
add the same behaviour to:
1) gene sets
2) pheno measure (in phenotype tool, family filters advanced tab, and wherever is also used)


gene browser:
1) clear input on click after a gene has been selected
2) after inputting invalid gene and pressing enter or go, the user no longer can make a query even with a valid gene

agp:
1) pressing the escape key on empty search triggers agp loadig spinner for 1 second (rebase master into branch to fix issue with table refreshing on escape)

2023-04-25 12:40 UTC, iordanivanov requested changes
AGP:
- Pressing the escape button on a cleared input field will re-send a request for all rows. Make it so that clearing an already cleared input does nothing.

Gene browser:
- Clicking on the input field after a query has been made should clear the input text.

Pheno browser:
- Pressing escape does not clear the input field.

2023-05-16 09:27 UTC, joankosev commented
bug: jumping input focus from one component to another on escape button press
(also exists in genotype browser when gene sets and advanced family measures are opened, check on other places too..)
https://github.com/iossifovlab/gpfjs/assets/50270882/8f3a5346-cd50-4caf-81a3-edd80d82a407

2023-05-17 08:52 UTC, closed without merging