Table now is more consistent when resized#764
iossifovlab/gpfjs pull request #774
Opened 2023-03-16 13:22 UTC by livovachkov

## Background

When the table is resized, it affects headers in a way breaking their width.

## Aim

Provide stability when the table is resized. The sticky headers should not scale with the current width but take the table width.

## Implementation

Closes #764.

2023-03-21 12:07 UTC, joankosev requested changes
doesn't work

https://user-images.githubusercontent.com/50270882/226601305-9a972302-a015-46c9-8ecf-907e012634e4.mp4

2023-03-30 13:24 UTC, joankosev commented
table/head should have min height

![image](https://user-images.githubusercontent.com/50270882/228850333-6751a492-b0f8-41de-8d61-9659fc68d52c.png)

2023-04-11 13:07 UTC, joankosev requested changes
the headers can overlap

http://dory.seqpipe.org:8000/hg38/datasets/ABN_genotypes/genotype-browser
![image](https://user-images.githubusercontent.com/50270882/231171769-8cf3768c-2033-41c7-b55e-9d5df3d91e00.png)

2023-05-03 10:08 UTC, joankosev commented
doesn't work
http://localhost:4200/datasets/denovo_db_liftover/genotype-browser
1300 width

2023-05-16 08:46 UTC, iordanivanov requested changes

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
> +    //this.tableWidth = this.tableViewChild?.nativeElement.offsetWidth;
Commented-out code

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/view/header/header.component.ts
> +  }
Empty event listener function

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/view/header/header-cell.component.html
> +          <span style="word-break: break-word" *ngIf="columnInfo.caption">{{ columnInfo.caption }}</span>
Minor nitpick - put the `ngIf` before the `style` attribute - it's more important not to miss it when reading the template

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/view/header/header-cell.component.html
> +          <span style="word-break: nowrap" *ngIf="!child.contentTemplateRef">{{ child.caption }}</span>
Minor nitpick - put the `ngIf` before the `style` attribute - it's more important not to miss it when reading the template

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
> +      this.tableWidth += 'px';
Don't convert this to string and float on every loop, just work with a float value and convert it to string after the loop has finished.

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
> +      this.tableWidth += 'px';
Don't convert this to string and float on every loop, just work with a float value and convert it to string after the loop has finished.

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
> +      }
Perhaps the final conversion of `tableWidth` to a string value should be done after this `if` to avoid yet another conversion to float

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
> +      }
Perhaps the final conversion of `tableWidth` to a string value should be done after this `if` to avoid yet another conversion to float

2023-05-16 08:46 UTC, iordanivanov commented on src/app/table/table.component.ts
>    public getVisibleData(): Array<any> {
The code in this function is identical to the one in the `onWindowResize` function - you should extract it to a single method

2023-05-18 10:26 UTC, joankosev commented
sticky table issue
![image](https://github.com/iossifovlab/gpfjs/assets/50270882/cccf9b07-21e9-41cf-83a2-ab0049b23654)
https://github.com/iossifovlab/gpfjs/assets/50270882/34a19ec3-17b7-498c-adb3-0c196b75a634

2023-05-19 12:03 UTC, joankosev commented
completely breaks in phenotype browser too

![image](https://github.com/iossifovlab/gpfjs/assets/50270882/71f91792-e2ac-46ad-9b07-356bcbeb16df)

2023-06-27 12:20 UTC, joankosev requested changes

2023-06-27 12:20 UTC, joankosev commented on src/app/table/view/header/header.component.ts
> +  public constructor(private cd: ChangeDetectorRef) {}
rename "cd" variable to either "cdr" or "changeDetectorRef"

2023-06-27 12:20 UTC, joankosev commented on src/app/pheno-browser-table/pheno-browser-table.component.ts
> +  private columnsCount = 8; // This is the number of columns
redundant comment

2023-06-27 13:43 UTC, joankosev approved these changes

2023-06-27 13:47 UTC, iordanivanov commented on src/app/table/table.component.ts
> +    this.tableWidth = String(this.calculateTableWidthFloat()) + 'px';
Same remark with format strings applies here

2023-06-27 13:48 UTC, iordanivanov commented on src/app/table/table.component.ts
> +    this.tableWidth = String(this.calculateTableWidthFloat()) + 'px';
Same remark with format strings applies here

2023-06-27 13:49 UTC, iordanivanov commented on src/app/table/view/header/header.component.html
> +    [style.max-width]="column.columnWidth ? column.columnWidth : null"
Could use an OR operator here `column.columnWidth || null`

2023-06-27 13:49 UTC, iordanivanov commented on src/app/table/table.component.html
>        [style.max-width]="column.columnWidth ? column.columnWidth : null"
Could use an OR operator here `column.columnWidth || null`

2023-06-27 13:53 UTC, iordanivanov requested changes

2023-06-27 13:53 UTC, iordanivanov commented on src/app/table/table.component.ts
> +    if (this.columnsChildren !== undefined && this.columnsChildren !== null) {
Invert this condition so that it works as a return guard, could also use `if (!this.columnsChildren)`

2023-06-30 10:56 UTC, iordanivanov approved these changes

2023-06-30 13:09 UTC, merged