Gene browser download buttons redesign
iossifovlab/gpfjs pull request #777
Opened 2023-03-22 11:39 UTC by IlinaGergova

design and position

## Background

The position of download summary varinats and download family varinats buttons didn't look well and the readability was poor.

## Aim

To change buttons position and design.

## Implementation

Put an icon instead of text on the buttons. Put the buttons next to their relevant counter .

2023-03-23 13:03 UTC, joankosev requested changes
1) ? unique family variants - does it change family variants download?
2) ? downloads are available even when the selected variants are 0, should we disable them?
3) remove download animation - we are moving towards the browser indicating the download
I'm not sure about the decision to merge the families download button and unique family variants field

2023-03-23 13:03 UTC, joankosev commented on src/app/gene-browser/gene-browser.component.ts
> +      this.isUniqueFamilyFitlerEnable = true;
isUniqueFamilyFitlerEnable -> isUniqueFamilyFitlerEnabled

2023-03-24 10:25 UTC, IvoStefanov approved these changes

2023-03-24 12:18 UTC, joankosev approved these changes

2023-03-24 13:11 UTC, merged