Streaming downloads
iossifovlab/gpfjs pull request #815
Opened 2023-04-21 13:49 UTC by iordanivanov

## Background

After we migrated to OAuth, we had to rework many of our POST downloads that used "form" elements to use Angular's HttpClient in order to attach Authorization headers. This however made downloads wait for the entire content to be streamed before saving it at once, due to technical limitations of Angular. On the user side, it appeared as if the client didn't not respond at all when clicking a download button.

## Aim

Make downloads instant and appear to actually "stream" the download instead of waiting for the whole response to fill up in memory.

## Implementation

We used the native fetch API and [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) with a self-hosted MITM to make downloads appear instantly and show progress.

2023-04-24 07:45 UTC, IvoStefanov submitted a review, later dismissed

2023-04-24 07:45 UTC, IvoStefanov commented on src/app/gene-browser/gene-browser.component.spec.ts
> +    // TODO
Test

2023-04-24 10:55 UTC, joankosev requested changes
1) remove unnecessary download animation in the gene browser
2) remove text change (download -> downloading...)

2023-04-26 12:51 UTC, joankosev approved these changes

2023-04-27 07:01 UTC, merged