Update icons
iossifovlab/gpfjs pull request #925
Opened 2023-10-09 10:45 UTC by IlinaGergova

## Background

The icons used in the project are mixed - pngs, html entities, symbols that are copy pasted, etc. Some of these icons won't be rendered if the used font doesn't have glif for the symbol.

## Aim

To replace Font awesome with Material and to import all used icons from Material.

2023-10-12 12:31 UTC, IvoStefanov requested changes

2023-10-12 12:31 UTC, IvoStefanov commented on src/app/sorting-buttons/sorting-buttons.component.html
> +  <span *ngIf="hideState === 0" id="bg" class="material-symbols-outlined">unfold_more</span>
Make a bit smaller to match the double arrows size.

2023-10-12 12:31 UTC, IvoStefanov commented on src/app/users-table/users-table.component.html
> +                [iconStyle]="{ name: 'close', class: 'material-symbols-outlined sm bold' }">
Align button with text.

2023-10-12 12:31 UTC, IvoStefanov commented on src/app/users-table/users-table.component.html
> +              [iconStyle]="{ name: 'refresh', class: 'material-symbols-outlined bold' }">
Align action buttons vertically (in center)

2023-10-24 10:05 UTC, joankosev submitted a review, later dismissed
federation token page:
- the edit icon and the X icon after edit, aren't aligned
- on credential creation, copy icon isn't aligned

Share quest modal in genotype browser:
- Copy icon should have other cursor on mouseover

Phenotype tool:
- measurement X icon isn't centered

AGP:
- burger icons are a bit bulky, try making them more small/delicate

2023-10-26 09:25 UTC, IvoStefanov approved these changes

2023-10-26 09:29 UTC, merged